name: Tests

on:
  pull_request:
    paths: 
      - dist/
      - .github/workflows/test_github_action.yml
  schedule:
    - cron: '0 8 * * *'

jobs:
  test-ubuntu:
    name: Run tests on ${{ matrix.os }} ${{ matrix.v-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        v-version: [latest, master, 0.1.29]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up V version latest
      uses: ./
      with:
        v-version: ${{ matrix.v-version }}
      id: v

    - name: Show V directory
      run: ls -lia ${{ steps.v.outputs.v_home }}
      
    - name: Test V is present
      run: v version
      
    - name: Test V fmt
      run: v fmt word_counter.v
      working-directory: ${{ steps.v.outputs.v_home }}/examples/word_counter

    - name: Test V can compile something
      run: v build word_counter.v
      working-directory: ${{ steps.v.outputs.v_home }}/examples/word_counter
      
    - name: Test compiled program
      run: ./word_counter cinderella.txt
      working-directory: ${{ steps.v.outputs.v_home }}/examples/word_counter
